@startuml

class Текстовый_Редактор {
 +new
 +newDoc()
}

class Документ {
    +ID
    +Имя
    +ДатаСоздания
    +ДатаРедактирования
    +new()
    +save()
    +print()
}

class Лист {
    +ID
    +Имя
    +copy()
    +edit()
    +delete()
}

class Текст {
    +font
    +size
    +add()
    +changeFont()
    +bold()
}

Текстовый_Редактор -- Документ : Создать
Документ o-- Лист: Существует в
Лист -- Текст
@enduml