@startuml
left to right direction
skinparam packageStyle rectangle
actor Пользователь

Пользователь -- (Открыть файл)
Пользователь -up- (Редактировать файл)
Пользователь -- (Печатать файл)
Пользователь -- (Создать файл)
Пользователь -- (Открыть специальный формат)
Пользователь -- (Сохранить файл)
Пользователь -- (Закрыть файл)

(Редактировать файл) .left-> (Добавить объект) : include
(Редактировать файл) .left-> (Удалить объект) : include
(Редактировать файл) .> (Заменить объект) : include
(Редактировать файл) .> (Найти объект) : include

(Подсветка ключ.сл) .> (Открыть специальный формат) :extend 
@enduml
