@startuml

|Пользователь|
start
:Открыть файл;
if (Существует?) then (Да)
else (Нет)
:Создать файл;
endif
:Открытие файла;
:Редактирование файла;
:Сохранение файла;
:Закрытие файла;
stop

@enduml
