@startuml
Пользователь -> Интерфейс : Открыть
activate Пользователь
activate Интерфейс
Интерфейс -> Контроллер
deactivate Пользователь
activate Контроллер
deactivate Интерфейс
Контроллер -> Модель
activate Модель
deactivate Контроллер
Модель -> Модель
Модель --> Интерфейс
deactivate Модель
activate Интерфейс
Интерфейс -> Интерфейс :Обновить
Пользователь -> Интерфейс : Изменить
activate Пользователь
Интерфейс -> Контроллер
deactivate Пользователь
activate Контроллер
deactivate Интерфейс
Контроллер -> Модель
activate Модель
deactivate Контроллер
deactivate Модель
Пользователь -> Интерфейс : Сохранить
activate Пользователь
activate Интерфейс
Интерфейс -> Контроллер
deactivate Пользователь
activate Контроллер
deactivate Интерфейс
Контроллер -> Модель
activate Модель
deactivate Контроллер
Модель -> Модель
Модель --> Интерфейс
deactivate Модель
activate Интерфейс
Интерфейс -> Интерфейс :Обновить
@enduml
